# Generated by Django 5.2.4 on 2025-08-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectjoinrequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='projectjoinrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Recusada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='projectjoinrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
